version: '3.7'

services:
  redis:
    image: redis:5.0-rc5-alpine
    volumes:
      - "./data:/data"
    restart: always
  proxy_scraper:
    build:
      context: .
      dockerfile: ./docker/proxy_scraper/Dockerfile
    depends_on:
      - redis
